### ISSUE TITLE
Steam does not execute

### ISSUE THREAD

**Issue by Lend27** [agajews/ApricityOS#20]
Double clicking the icon does nothing.

**Comment by agajews** [comment]
Steam is a 32-bit program. Even when you install the "64-bit" version, it's still 32-bit. Therefore, it has 32-bit needs. The reason it won't start by default is because it needs the 32-bit version of your graphics driver installed. For details as to what packages need to be installed for your specific card, look at this page:

https://wiki.archlinux.org/index.php/Xorg#Driver_installation

In one case, a user had to install lib32-nvidia-340xx-libgl in order for Steam to start on my Nvidia based system. Once they did, it started right up and started updating. Prior to that, it did nothing and running it from a terminal returned a driver error. Also, in order to have sound on a 64-bit system, you need to install lib32-alsa-plugins. This is necessary no matter what your architecture. Further tips and troubleshooting for Steam on Arch can be found here:

https://wiki.archlinux.org/index.php/Steam

We're working on resolving this issue for the October Beta release.

**Comment by gogobebe2** [comment]
> We're working on resolving this issue for the October Beta release. 
So what do you plan on doing to resolve it?

**Comment by agajews** [comment]
I think it may be as simple as enabling bumblebee by default. It should automatically select libgl stuff when properly enabled.

**Comment by gogobebe2** [comment]
Oh ok, thanks for the info.

**Comment by Murii** [comment]
Is this issue fixed?

**Comment by agajews** [comment]
There is a new beta being released this week that has bumblebee enabled by default which may fix the issue, but unfortunately I can't be sure because nobody on the Apricity OS Team has an Nvidia card to test this with. The issue can always be fixed with the instructions at the aforementioned link, it's just a question of whether or not it works by default.

**Comment by heil-stalin** [comment]
Issue is not fixed.

i7 6700k
AMD HD 7950 / mesa
Such a beautiful OS, but bugs are not being fixed.

**Comment by agajews** [comment]
Try running this:

$ cd .local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/
$ mv libstdc++.so.6.0.18 libstdc++.so.6.0.18.remove
$ rm libstdc++.so.6

$ cd ~/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/
$ mv libstdc++.so.6.0.18 libstdc++.so.6.0.18.remove
$ rm libstdc++.so.6

**Comment by heil-stalin** [comment]
Already got rid of Apricity. You can't tout Steam (and all the other preinstalled programs) being in the OS already when they don't even work. Did you even try to start Steam on a 64bit only OS?

It has a lot of potential, and I would love to use it one day. Until then, keep ironing out bugs.

**Comment by heil-stalin** [comment]
Since I still had the ISO laying around, I decided to throw it in a VM and try what you suggested. There is no amd64 folder in the steam runtime. 

https://i.imgur.com/C3JyCI9.png

**Comment by heil-stalin** [comment]
So, this just worked. 

LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1' steam

**Comment by Cauterize-Linux** [comment]
As @heil-stalin mentioned here in the Arch Wiki this is documented work around for Arch in general not just Apricity OS. 

https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Work_arounds

**Comment by heil-stalin** [comment]
It worked once. I restarted, and tried to just launch steam normally and it wouldn't. I then I ran the same exact commands as I did before, but it didn't work.

**Comment by Cauterize-Linux** [comment]
Have you tried using this? It is the first command under deleting the runtime libraries

find ~/.steam/root/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" -o -name "libgpg-error.so*" \) -print -delete

**Comment by cgarey2014** [comment]
I got it to work just fine. I ran the command Cauterize-Linux suggested, then the LD_PRELOAD command and got it to update. After it updated, I re-ran the first command, and it worked just fine. I'm fairly certain this is not an Apricity bug, I have had this issue in several distros before.

**Comment by heil-stalin** [comment]
Have you restarted your computer multiple times? As soon as mine restarted
after finally getting Steam to work, it never worked after that.

**Comment by cgarey2014** [comment]
I haven't. I'm in the middle of a project, but when I have a chance I'll try to.

**Comment by cgarey2014** [comment]
I have restarted multiple times and steam works just fine.
